#!/bin/bash
echo "Fetching 1/15: https://hackillinois.org/travel"
echo "Fetching 2/15: https://tartanhacks.com/"
echo "Fetching 3/15: https://hackpsu.org/travel"
echo "Fetching 4/15: https://efest.biz/"
echo "Fetching 5/15: https://www.unh.edu/ecenter/students/student-competitions"
echo "Fetching 6/15: https://www.smeal.psu.edu/sustainability/land-grant-launch"
echo "Fetching 7/15: https://www.techconnectworld.com/World2026/students/ETMWD/form.html"
echo "Fetching 8/15: https://cra.org/ur2phd/for-undergraduate-students/funding/technical-conference-travel-funding-funding-eligibility-for-undergraduate-students"
echo "Fetching 9/15: https://academics.utahtech.edu/ro/student-grants/travel-grants-application/"
echo "Fetching 10/15: http://www.conradchallenge.com/"
echo "Fetching 11/15: https://www.pdma.org/page/student-innovation-challenge"
echo "Fetching 12/15: https://www.nasa.gov/directorates/stmd/prizes-challenges-crowdsourcing-program/center-of-excellence-for-collaborative-innovation-coeci/nasa-techrise-student-challenge-5/"
echo "Fetching 13/15: https://foundation.llvm.org/grants-scholarships"
echo "Fetching 14/15: https://oedit.colorado.gov/governors-tourism-conference-student-scholarship"
echo "Fetching 15/15: https://women.acm.org/scholarships/"
